version: '2'
services:
    myreactapp-mongodb:
        image: mongo:3.4.8
        ports:
            - "27017:27017"
        command: mongos --configdb myreactapp-mongodb-config
    myreactapp-mongodb-node:
        build:
            context: .
            dockerfile: mongodb/MongoDB.Dockerfile
        command: mongod --replSet rs1 --noprealloc --smallfiles
    myreactapp-mongodb-config:
        image: mongo:3.4.8
        container_name: myreactapp-mongodb-config
        command: mongod --noprealloc --smallfiles --configsvr --dbpath /data/db
